/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.apache.poi.xssf.usermodel.XSSFWorkbook
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream

data class StudentRecord(
    val name: String,
    val score: Double?,
    val grade: String
)

class StudentGradeCalculator(private val inputFile: String) {
    private val outputFile = File(inputFile).parentFile?.let { 
        File(it, "grades_output.xlsx") 
    } ?: File("grades_output.xlsx")

    fun process() {
        try {
            val students = readExcelFile()
            
            if (students.isEmpty()) {
                println("Error: No valid student records found in the file.")
                return
            }
            
            writeExcelFile(students)
            printSummaryTable(students)
        } catch (e: Exception) {
            println("Error processing file: ${e.message}")
            e.printStackTrace()
        }
    }

    private fun readExcelFile(): List<StudentRecord> {
        val records = mutableListOf<StudentRecord>()
        
        FileInputStream(inputFile).use { fis ->
            val workbook = XSSFWorkbook(fis)
            val sheet = workbook.getSheetAt(0)
            
            var rowIndex = 0
            for (row in sheet) {
                rowIndex++
                
                // Skip header row (first row)
                if (rowIndex == 1) continue
                
                val nameCell = row.getCell(0)
                val scoreCell = row.getCell(1)
                
                val name = nameCell?.stringCellValue?.trim() ?: ""
                var score: Double? = null
                var isValid = true
                
                // Validate and extract score
                if (name.isEmpty()) {
                    isValid = false
                } else if (scoreCell == null || scoreCell.cellType == org.apache.poi.ss.usermodel.CellType.BLANK) {
                    isValid = false
                } else {
                    try {
                        score = when (scoreCell.cellType) {
                            org.apache.poi.ss.usermodel.CellType.NUMERIC -> scoreCell.numericCellValue
                            org.apache.poi.ss.usermodel.CellType.STRING -> {
                                val scoreStr = scoreCell.stringCellValue.trim()
                                scoreStr.toDouble()
                            }
                            else -> {
                                isValid = false
                                null
                            }
                        }
                        
                        if (score != null && (score < 0 || score > 100)) {
                            isValid = false
                            score = null
                        }
                    } catch (e: Exception) {
                        isValid = false
                    }
                }
                
                val grade = if (isValid && score != null) assignGrade(score) else "Invalid"
                records.add(StudentRecord(name.ifEmpty { "Unknown" }, score, grade))
            }
            
            workbook.close()
        }
        
        return records
    }

    private fun assignGrade(score: Double): String {
        return when {
            score >= 90 -> "A"
            score >= 80 -> "B"
            score >= 70 -> "C"
            score >= 60 -> "D"
            else -> "F"
        }
    }

    private fun writeExcelFile(students: List<StudentRecord>) {
        XSSFWorkbook().use { workbook ->
            val sheet = workbook.createSheet("Grades")
            
            // Create header row
            val headerRow = sheet.createRow(0)
            headerRow.createCell(0).setCellValue("Name")
            headerRow.createCell(1).setCellValue("Score")
            headerRow.createCell(2).setCellValue("Grade")
            
            // Style the header row
            val headerStyle = workbook.createCellStyle()
            val headerFont = workbook.createFont()
            headerFont.bold = true
            headerStyle.setFont(headerFont)
            for (i in 0..2) {
                headerRow.getCell(i).cellStyle = headerStyle
            }
            
            // Write data rows
            var rowIndex = 1
            for (student in students) {
                val row = sheet.createRow(rowIndex++)
                row.createCell(0).setCellValue(student.name)
                if (student.score != null) {
                    row.createCell(1).setCellValue(student.score)
                } else {
                    row.createCell(1).setCellValue("")
                }
                row.createCell(2).setCellValue(student.grade)
            }
            
            // Auto-fit column widths
            sheet.autoSizeColumn(0)
            sheet.autoSizeColumn(1)
            sheet.autoSizeColumn(2)
            
            // Write to file
            FileOutputStream(outputFile).use { fos ->
                workbook.write(fos)
            }
        }
        
        println("\nOutput file created: ${outputFile.absolutePath}")
    }

    private fun printSummaryTable(students: List<StudentRecord>) {
        println("\n" + "=".repeat(60))
        println("STUDENT GRADE SUMMARY")
        println("=".repeat(60))
        println(String.format("%-25s | %-10s | %-10s", "Name", "Score", "Grade"))
        println("-".repeat(60))
        
        for (student in students) {
            val scoreStr = if (student.score != null) String.format("%.2f", student.score) else "N/A"
            println(String.format("%-25s | %-10s | %-10s", student.name, scoreStr, student.grade))
        }
        
        println("=".repeat(60))
        
        // Print statistics
        val validStudents = students.filter { it.score != null }
        if (validStudents.isNotEmpty()) {
            val avgScore = validStudents.map { it.score ?: 0.0 }.average()
            println(String.format("Total Students: %d | Average Score: %.2f", students.size, avgScore))
        } else {
            println("Total Students: ${students.size}")
        }
        
        println("=".repeat(60) + "\n")
    }
}

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("Error: Please provide the input Excel file as an argument.")
        println("Usage: ./gradlew run --args=\"students.xlsx\"")
        return
    }
    
    val inputFile = args[0]
    val file = File(inputFile)
    
    if (!file.exists()) {
        println("Error: File '$inputFile' not found.")
        return
    }
    
    println("Processing file: $inputFile")
    val calculator = StudentGradeCalculator(inputFile)
    calculator.process()
}
