/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.apache.poi.ss.usermodel.CellType
import org.apache.poi.xssf.usermodel.XSSFWorkbook
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream

data class StudentRecord(
    val name: String,
    val score: Double?,
    val grade: String
)

class StudentGradeCalculator(private val inputFile: String) {
    private val outputFile = File(inputFile).parentFile?.let { 
        File(it, "grades_output.xlsx") 
    } ?: File("grades_output.xlsx")

    fun process() {
        try {
            val students = readExcelFile()
            
            if (students.isEmpty()) {
                println("Error: No valid student records found in the file.")
                return
            }
            
            writeExcelFile(students)
            printSummaryTable(students)
        } catch (e: Exception) {
            println("Error processing file: ${e.message}")
            e.printStackTrace()
        }
    }

    private fun readExcelFile(): List<StudentRecord> {
        FileInputStream(inputFile).use { fis ->
            XSSFWorkbook(fis).use { workbook ->
                val sheet = workbook.getSheetAt(0)

                return sheet
                    .filterIndexed { index, _ -> index > 0 } // Skip header row
                    .map { row ->
                        val nameCell = row.getCell(0)
                        val scoreCell = row.getCell(1)

                        val name = nameCell?.stringCellValue?.trim() ?: ""
                        var score: Double? = null
                        var isValid = true

                        if (name.isEmpty()) {
                            isValid = false
                        } else if (scoreCell == null || scoreCell.cellType == CellType.BLANK) {
                            isValid = false
                        } else {
                            try {
                                score = when (scoreCell.cellType) {
                                    CellType.NUMERIC -> scoreCell.numericCellValue
                                    CellType.STRING -> scoreCell.stringCellValue.trim().toDouble()
                                    else -> {
                                        isValid = false
                                        null
                                    }
                                }

                                if (score != null && (score < 0 || score > 100)) {
                                    isValid = false
                                    score = null
                                }
                            } catch (_: Exception) {
                                isValid = false
                            }
                        }

                        val grade = if (isValid && score != null) assignGrade(score) else "Invalid"
                        StudentRecord(name.ifEmpty { "Unknown" }, score, grade)
                    }
            }
        }
    }

    private fun assignGrade(score: Double): String {
        return when {
            score >= 90 -> "A"
            score >= 80 -> "B"
            score >= 70 -> "C"
            score >= 60 -> "D"
            else -> "F"
        }
    }

    private fun writeExcelFile(students: List<StudentRecord>) {
        XSSFWorkbook().use { workbook ->
            val sheet = workbook.createSheet("Grades")

            // Create header row
            val headerRow = sheet.createRow(0)
            headerRow.createCell(0).setCellValue("Name")
            headerRow.createCell(1).setCellValue("Score")
            headerRow.createCell(2).setCellValue("Grade")
            
            // Style the header row
            val headerStyle = workbook.createCellStyle()
            val headerFont = workbook.createFont()
            headerFont.bold = true
            headerStyle.setFont(headerFont)
            (0..2)
                .map(headerRow::getCell)
                .filterNotNull()
                .forEach { it.cellStyle = headerStyle }

            students.forEachIndexed { index, student ->
                val row = sheet.createRow(index + 1)
                row.createCell(0).setCellValue(student.name)
                if (student.score != null) {
                    row.createCell(1).setCellValue(student.score)
                } else {
                    row.createCell(1).setCellValue("")
                }
                row.createCell(2).setCellValue(student.grade)
            }
            
            // Auto-fit column widths
            sheet.autoSizeColumn(0)
            sheet.autoSizeColumn(1)
            sheet.autoSizeColumn(2)
            
            // Write to file
            FileOutputStream(outputFile).use { fos ->
                workbook.write(fos)
            }
        }
        
        println("\nOutput file created: ${outputFile.absolutePath}")
    }

    private fun printSummaryTable(students: List<StudentRecord>) {
        println("\n" + "=".repeat(60))
        println("STUDENT GRADE SUMMARY")
        println("=".repeat(60))
        println(String.format("%-25s | %-10s | %-10s", "Name", "Score", "Grade"))
        println("-".repeat(60))
        
        students
            .map { student ->
                val scoreStr = student.score?.let { String.format("%.2f", it) } ?: "N/A"
                String.format("%-25s | %-10s | %-10s", student.name, scoreStr, student.grade)
            }
            .forEach(::println)

        println("=".repeat(60))
        
        val validStudents = students.filter { it.score != null }
        if (validStudents.isNotEmpty()) {
            val avgScore = validStudents.map { it.score ?: 0.0 }.average()
            println(String.format("Total Students: %d | Average Score: %.2f", students.size, avgScore))
        } else {
            println("Total Students: ${students.size}")
        }
        
        println("=".repeat(60) + "\n")
    }
}

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("Error: Please provide the input Excel file as an argument.")
        println("Usage: ./gradlew run --args=\"students.xlsx\"")
        return
    }
    
    val inputFile = args[0]
    val file = File(inputFile)
    
    if (!file.exists()) {
        println("Error: File '$inputFile' not found.")
        return
    }
    
    println("Processing file: $inputFile")
    val calculator = StudentGradeCalculator(inputFile)
    calculator.process()
}
